version: '3.8'
services:
    db:
        image: postgres
        container_name: database
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: tesla
            POSTGRES_PASSWORD: tesla
        ports:
            - "5432:5432"
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        depends_on:
            - db
    nginx:
        build:
            context: .
            dockerfile: ./Dockerfile.nginx
        container_name: nginx
        ports:
            - 80:80
        depends_on:
            - app
        volumes:
            - .:/app
        links:
            - app
volumes:
    postgres_data: