version: "3.9"
services:
    db:
        image: postgres
        container_name: database
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_PASSWORD: tesla
        expose:
            - "5432"
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - .:/app
        expose:
            - "3000"
        depends_on:
            - db
    nginx:
        build:
            context: .
            dockerfile: ./Dockerfile.nginx
        container_name: nginx
        ports:
            - 80:80
        depends_on:
            - app
        volumes:
            - .:/app
        links:
            - app
