# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup app
        working-directory: ./aplicacao
        run: docker-compose up -d

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare db
        working-directory: ./aplicacao
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          RAILS_ENV: test
          POSTGRES_USER: tesla
          POSTGRES_PASSWORD: tesla
        run: docker-compose run app rails db:reset
      - name: Run tests
        working-directory: ./aplicacao
        run: docker-compose run app rspec

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        working-directory: ./aplicacao
        run: |
          docker-compose run app bash -c "bundle exec rubocop --config .rubocop.yml --parallel"
